export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as Collectibles } from './Collectibles'
export { default as QRCode } from './QRCode'
export { default as Create } from './Create'
export { default as Get } from './Get'
